jwt:
  secret: *******
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://*********:3306/recipe?autoReconnect=true
    username: *******
    password: *********
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 177000
  jpa:
    database: mysql   # 추가 해준 부분
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update # 자동으로 테이블을 만들어줌 애플리케이션 실행시에 다 지우고 다시 실행
    properties:
      hibernate:
        show_sql: true
        format_sql: true
